name: taox11

on:
  push:
    branches:
      - master
      - v*
    tags:
      - AXCIOMA-v*
  pull_request:
    branches:
      - master
      - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  X11_BRANCH: BAR

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            CC: gcc-7
            CXX: g++-7
            ruby: '2.5'
            PackageDeps: g++-7
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.CXX }} ruby-${{ matrix.ruby }}
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    steps:
    - if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name) 
      run: |
        echo "X11_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
    - if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name) == false
      run: |
        echo "X11_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: checkout taox11
      uses: actions/checkout@v3
      with:
        repository: RemedyIT/taox11
        path: ${{ env.TAOX11_ROOT }}
        ref: ${{ env.X11_BRANCH }}
  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            ruby: '3.0'
            project_type: vs2019
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ruby-${{ matrix.ruby }} ${{ matrix.project_type }}
    steps:
    - if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name) && github.repository_owner == 'RemedyIT'
      run: |
        echo "X11_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
    - if: contains(fromJson('["pull_request", "pull_request_target"]'), github.event_name) == false && github.repository_owner == 'RemedyIT'
      run: |
        echo "X11_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: checkout taox11
      uses: actions/checkout@v3
      with:
        repository: RemedyIT/taox11
        path: ${{ env.TAOX11_ROOT }}
        ref: ${{ env.X11_BRANCH }}
